import { resolvePackageName, getClient } from "../resolve.js";
import type { Command } from "commander";
import { loadConfig } from "@gpc-cli/config";

import { listGeneratedApks, downloadGeneratedApk, formatOutput } from "@gpc-cli/core";
import { getOutputFormat } from "../format.js";

export function registerGeneratedApksCommands(program: Command): void {
  const cmd = program
    .command("generated-apks")
    .description("Manage device-specific APKs generated by Google Play");

  cmd
    .command("list <version-code>")
    .description("List generated APKs for a version code")
    .action(async (versionCodeStr: string) => {
      const config = await loadConfig();
      const packageName = resolvePackageName(program.opts()["app"], config);
      const client = await getClient(config);
      const format = getOutputFormat(program, config);

      const versionCode = parseInt(versionCodeStr, 10);
      if (isNaN(versionCode)) {
        const err = new Error("version-code must be a number");
        Object.assign(err, { code: "USAGE_ERROR", exitCode: 2 });
        throw err;
      }

      const result = await listGeneratedApks(client, packageName, versionCode);
      if (format !== "json") {
        const apks = (result as unknown as Record<string, unknown>)["generatedApks"] as
          | Array<Record<string, unknown>>
          | undefined;
        if (apks && apks.length > 0) {
          const rows = apks.map((apk) => ({
            id: apk["generatedApkId"] || "-",
            variantId: apk["variantId"] || "-",
            moduleName: apk["moduleName"] || "-",
            sha256: String(apk["certificateSha256Fingerprint"] || "-").slice(0, 16) + "...",
          }));
          console.log(formatOutput(rows, format));
        } else {
          console.log("No generated APKs found.");
        }
      } else {
        console.log(formatOutput(result, format));
      }
    });

  cmd
    .command("download <version-code> <apk-id>")
    .description("Download a generated APK")
    .requiredOption("--output <path>", "Output file path")
    .action(async (versionCodeStr: string, apkId: string, opts: { output: string }) => {
      const config = await loadConfig();
      const packageName = resolvePackageName(program.opts()["app"], config);
      const client = await getClient(config);
      const format = getOutputFormat(program, config);

      const versionCode = parseInt(versionCodeStr, 10);
      if (isNaN(versionCode)) {
        const err = new Error("version-code must be a number");
        Object.assign(err, { code: "USAGE_ERROR", exitCode: 2 });
        throw err;
      }

      const result = await downloadGeneratedApk(
        client,
        packageName,
        versionCode,
        apkId,
        opts.output,
      );
      console.log(formatOutput(result, format));
    });
}
